### ISSUE TITLE
GnGeo emulator

### ISSUE THREAD

**Issue by mgoulartBR** [digitalLumberjack/recalbox-os#11]
Hi!

I'm trying to play some recent games from SNK on piFBA (KOF 2002, for example) and I'm just getting black screens. I saw on this link http://pimame.org/forum/discussion/1205/large-roms-on-fba-garou-kof2005-and-others-not-working-/p1 that the problem was solved only when they were emulated on GnGeo.

**Comment by digitalLumberjack** [comment]
Hi, garou, KOF 2002 and 2003 pass well on pifba.
Use https://code.google.com/p/pifba/source/browse/FBAcapex_src/gamelist.txt?spec=svn018b31d990231eccae5c57690cb5a4d55b6fa0e2&r=018b31d990231eccae5c57690cb5a4d55b6fa0e2 for the compatibility list and use https://pifba.googlecode.com/git/fba_029671_clrmame_dat.zip dat file with clrmamepro in order to create rom corresponding with pifba compatible romset
