### ISSUE TITLE
psx emu won't load game

### ISSUE THREAD

**Issue by laurin92** [digitalLumberjack/recalbox-os#187]
downloaded some psx games, converted them into .iso with imgburn, started them, screen fades to black, after 5 sec back to the frontend.

**Comment by NerosTie** [comment]
Which Raspberry?

**Comment by digitalLumberjack** [comment]
Hi, the emulator is very sensible to the iso format.
Could you try not to convert them, test it in .cue/.bin format.

**Comment by Energizing** [comment]
convert them with isobuster, works fine with it

**Comment by digitalLumberjack** [comment]
@laurin92 any news ?

**Comment by laurin92** [comment]
sorry for the late answer, was unable to test it erlier again.
i'm using rpi 2 model B, recalbox v. 3.2.10

seems like the previous downloaded files had a strange format. tried it somewhere else, got .bin / .cue files and just copied them to the recalbox. works fine!
just having some fps issues, but i think thats because of the 3D graphics... psx may be too hard for the rpi2

**Comment by mezzb** [comment]
The emu supports iso, bin, cue and img, which covers all the files I've found (if you see one with ccd, sub, etc, there usually is still an img which contains the iso data.  if there is an ecm extension, it's a compression algorithm.  look for "ecm tools" to convert to standard img.

**Comment by Neo-1986** [comment]
I have the same issue. I got a 32GB SD Card, everything works perfect. Now I bought a 128GB Samsung SD Card, everything works perfect, too, except the psx emulator. game seems to load but returns to frontend after 5-7sec.
i installed recalbox on the new sd card. Then, I copied the working folders roms, saves, bios from the 32gb SD Card to my computer and copied them back to the 128gb share folder.
This way, I did not have to scrape games again. And as I said, everything except psx works perfect, even mame or neogeo which are quite difficult to run because you need the correct mame/rom version.

The whole copying and copying back to the sd card took about 10-12 hours. So I don`t want to format my sd card again (by the way, it came with exfat, i formatted it to fat32). 

Has someone an idea what the cause of the problem could be?

the bios, saves, roms folders of the two sd cards are identical and both run 4.0.1 version of recalbox, even the background music and controllers are the same ;)

hope to hear from you soon. kind regards Neo
