### ISSUE TITLE
Support xin-mo

### ISSUE THREAD

**Issue by digitalLumberjack** [digitalLumberjack/recalbox-os#284]
Is there a way to modify the driver in order to create two devices ? It would avoid so many configuration issues :)
@ian57 :D

**Comment by ian57** [comment]
Don't know... but wa ca

**Comment by pasnox** [comment]
The patch to enable 2 joysticks support with xin mo devices is located here: https://github.com/raspberrypi/linux/pull/828/files

I tested it on Raspbian, and now i can see 2 joysticks devices in /dev/input/js* instead of only one.
The patch consist to apply the 2lines patch to the kernel sources and build it (I do recommend cross building ...), then simply copy the new kernel at the location of the old one.

**Comment by digitalLumberjack** [comment]
That is GREAT

**Comment by ian57** [comment]
Very cool, simpler than I thought...
