### ISSUE TITLE
major bug with kingston 4GB micro sd cards

### ISSUE THREAD

**Issue by digitalLumberjack** [digitalLumberjack/recalbox-os#3]
from @symbios24 : 
there is a major bug with micro sd card kingston cards 4gb after installation is finish always get the message kernel panic and is not booting at all, also in the menu the option to install from the memory card is not available online install is available only, please fix this two thanks

**Comment by hstampfl** [comment]
One of my colleague do get a kernal panic while booting. It looks like the system works for several days /several boots the card get coruppted. The Card is from Transcend. 
I also saw this on my first installation, but since then I haven't seen this on my installation. I will try to get more Infos when it's happen again.

**Comment by digitalLumberjack** [comment]
I'm going to pull the last noob on recalbox-rescue soon. It should correct
many bugs.

**Comment by hstampfl** [comment]
cool, thanks

**Comment by digitalLumberjack** [comment]
I made the merge, could you retry with the last version of recalbox (release in few hours normally) and your SD card ? Thanks

https://github.com/digitalLumberjack/recalbox-rescue/commit/54439f2db1aeaad6ddd82d16a9d7ac0ca6f0c62b
