### ISSUE TITLE
Change keyboard map corresponding to language

### ISSUE THREAD

**Issue by digitalLumberjack** [digitalLumberjack/recalbox-os#34]

**Comment by digitalLumberjack** [comment]
The keyboard layout is now changed corresponding to the language choosen in the settings.

**Comment by th3m4ri0** [comment]
How about Quebec ? We have QWERTY keyboards but speak french ;)

**Comment by digitalLumberjack** [comment]
Damn ☺

**Comment by Churchill92** [comment]
Found a problem when trying to do an underscore (_) with the default english language for Wif . The default english language defaults to English(UK) not English(US). In this regard I cannot use several keys on the keyboard such as the _ key. 

This can be remedied by adding in support for locale instead of just keyboards. 

https://wiki.archlinux.org/index.php/Keyboard_configuration_in_console

**Comment by digitalLumberjack** [comment]
@Churchill92 yes this is an other issue : https://github.com/digitalLumberjack/recalbox-os/issues/37 
I close this one a the commit https://github.com/digitalLumberjack/recalbox-buildroot/commit/f5aebe4b664c7122c8be4fb4a1a05d6c84c8b4b0 allows fine tuning of language and keymap

**Comment by th3m4ri0** [comment]
Supercool :+1:
