### ISSUE TITLE
Add Controller support to Kodi

### ISSUE THREAD

**Issue by Guzilli** [digitalLumberjack/recalbox-os#350]
Would be great to navigate through kodi using a controller.

**Comment by reivaax** [comment]
Hi Guzilli :).
Next time, do a search before opening a new issue,)
https://github.com/digitalLumberjack/recalbox-os/issues/12

But a big +1 for your issue :).

Unfortunately we need to wait an update of kodi raspberry for pads support. because at the moment, it's not possible on raspberry version. Only on PC version.
