### ISSUE TITLE
Add Wiimote and Classic Controller support 

### ISSUE THREAD

**Issue by mynickistak** [digitalLumberjack/recalbox-os#424]
Classic Controller (Pro) ist just awesome for retro games and it's cheap. Is it possible to add it's support to Recalbox? I think it would bring some new users to Recalbox because RetroPie can't  handle classic controller, too*.
(*Or only with some terminal work which ist too complex for a lot of users)

**Comment by rockaddicted** [comment]
There an issue about that.
If you have hardware and knowledges, you can help to solve this problem.
https://github.com/digitalLumberjack/recalbox-os/issues/13
https://github.com/digitalLumberjack/recalbox-os/issues/14

**Comment by mynickistak** [comment]
Sorry and thanks for links. I have hardware but no really knowledges. Maybe I can be a beta tester or help something else. I will keep this issues in sight.

**Comment by nadenislamarre** [comment]
I'm working on that issue.
Basically, the issue is that linux driver make as if the wiimote is not a joystick ; indeed, it's not really, it's more a special device.
The delta can be fixed quite easyly for sd2 :

1) by addind some udev rules
SUBSYSTEM=="input", ATTRS{name}=="Nintendo Wii Remote Classic Controller", MODE="0666", ENV{ID_INPUT_JOYSTICK}="1"
SUBSYSTEM=="input", ATTRS{name}=="Nintendo Wii Remote", MODE="0666", ENV{ID_INPUT_JOYSTICK}="1"

2) by replacing in SDL2 joystick files, BTN_MISC by 0, because joysticks are supposed to have buttons over BTN_MISC. 4 buttons of the wiimote are KEY_LEFT, UP, DOWN, RIGH, under BTN_MISC and are therefore ignored for compatibility reason (sdl1 for example).

At the end, on my raspberry, i get the wiimote working. Unfortunally, as far as i start a game, it doesn't work anymore. I think it's because some things are based on sdl1 in recalbox. So i tried to fix sdl1, but it's harder.

So finally, i'm modifying the kernel driver of the wiimote to change the buttons keys over KEY_MISC.

For the controller, i guess it will not be enough, because on my computer, the hats have still some strnage behavior that must be fixed.

**Comment by nadenislamarre** [comment]
Job done for the wiimote. Require to apply a patch upstream.
Resume of the changes :

Summary of the 2 fixes :

1) make SDL2 considers any udev button
SDL2 ignores buttons which are not between BTN_MISC and KEY_MAX
RA_UDEV ignores buttons which are not between BTN_MISC and KEY_MAX or between KEY_UP and KEY_DOWN
2) make SDL2 assign buttons following the input.h file order as RA_UDEV does
an example joystick has 2 buttons : BTN_MISC and BTN_JOYSTICK

SDL2 will assign :
button 0 = BTN_JOYSTICK
button 1 = BTN_MISC

RA_UDEV will assign :
button 0 = BTN_MISC
button 1 = BTN_JOYSTICK

Buttons current behaviors :

SDL2:
between        0     and BTN_MISC-1     : ignored
between BTN_MISC     and BTN_JOYSTICK-1 : second buttons group
between BTN_JOYSTICK and KEY_MAX        : first buttons group

RA_UDEV:
between 0        and KEY_UP-1   : ignored
between KEY_UP   and KEY_DOWN-1 : first buttons group
between KEY_DOWN and BTN_MISC-1 : ignored
between BTN_MISC and KEY_MAX    : first buttons group

SDL2 updated to :
between 0 and KEY_MAX : first buttons group
no keys are ignored, so, potentially, we could update ra too if some poeple have buttons working in es but not in ra.
Risks :
1) SDL1 compatibiliy
theses modifications break compabitility between sdl1 and sdl2.
A joystick working with es but not working in ra could become not working on an other emulator based on sdl1.
2) Buttons reordering
A joystick configured in es could have to be reconfigured in case the buttons order has changed. However, if this occurs, it means that some buttons were already not working correctly in ra.
